name: "Meets"
title: "Meets"
description: "Meet other keebers in Norway"
baseurl: "/meets"
plugins:
  - jekyll-seo-tag
markdown: kramdown
encoding: UTF-8
timezone: Europe/Oslo
exclude: [LICENSE, README.md, Gemfile, Gemfile.lock]
